# Generated by Django 3.2.4 on 2021-07-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldermodel',
            name='folder_identifier',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wellmodel',
            name='well_identifier',
            field=models.CharField(max_length=200),
        ),
    ]
