# Generated by Django 3.2.4 on 2021-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatemodel',
            name='X',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coordinatemodel',
            name='Y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coordinatemodel',
            name='Z',
            field=models.FloatField(),
        ),
    ]
